name: Publish GitHub Packages
on:
    push:
        branches: [ main ]

permissions:
    contents: read
    packages: write

defaults:
    run:
        working-directory: ./lib

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: '20.x'
                  registry-url: 'https://npm.pkg.github.com'
                  scope: '@millipedesg'
            - run: yarn install --no-immutable
            - run: yarn build
            - name: Set CI version
              run: node -e "const fs=require('fs');const pkg=require('./package.json');const base=pkg.version.replace(/-milli\\.\\d+$/, '');const run=process.env.GITHUB_RUN_NUMBER;pkg.version=`${base}-milli.${run}`;fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));"
            - run: npm publish --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
